# Generated by Django 4.2 on 2023-05-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_liststudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='liststudent',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='liststudent',
            name='first_name',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AddField(
            model_name='liststudent',
            name='last_name',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
    ]
